import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/Components/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className=" bg-gradient-to-r from-[#1F3B2D] via-[#2D6A4F] to-[#355E4B]">

        {children}
        <Footer />
        </body>
    </html>
  );
}
